### ISSUE TITLE
Content Object IDS VARCHAR Causing Index Issues

### ISSUE THREAD

**Issue by djbp** [justquick/django-activity-stream#260]
I noticed that when the Activity object was first created, the content object object ids were integers and that migration 0004 converted them to VARCHAR(255).

This is causing issues for me when I run migration 0008:
`CREATE INDEX `actstream_action_verb_40b07f8ff547749c` ON `actstream_action` (`verb`,`action_object_object_id`,`timestamp`,`actor_object_id`,`target_object_id`,`public`);`
`The error was: (1071, 'Specified key was too long; max key length is 1000 bytes')`

Our project only uses int-based indexes - so the conversion to varchar will only have a negative impact on performance and bring no benefits.

Is there a possibility of perhaps having a branch which caters to those who only use int-based primary keys?

**Comment by justquick** [comment]
what database are you using? are your actstream FKs currently varchar or int?

i made a decision a while back to to varchar for maximum compatibility for things like UUIDFields. ints are much more performant but it also means that some apps (yours or 3rd party) might not work. that being said it's one of the biggest issues ive received 

maintaining two separate branches is not a long term solution that would require two different release tracks. i think instead of having 2 branches we could have it be a setting (USE_CHARFIELDS=True) that conditionally effects the migrations. im just spit balling and there are probably tons of reasons not to do that

**Comment by djbp** [comment]
I am using MySQL, MyISAM database engine - though may switch the DB over to InnoDB at some point.

I did wonder about having a setting such as the one you describe, though I'd have a concern that it might make South migrations really hard to maintain (I may be wrong about that though). As far as I understand it, a migration file, as well as including the forwards and backward migrations, also includes a snapshot of the table structure prior to the migration - this would either have to be hand-edited per migration - or something else. I don't know enough about migrations to know how much they can be affected by Django settings files.

`` models = {
        'actstream.action': {
            'action_object_object_id': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True', 'blank': 'True'}),
            ...
        }
}``

**Comment by justquick** [comment]
I do a little of customization in the migration with relation to the custom user model

https://github.com/justquick/django-activity-stream/blob/master/actstream/south_migrations/0005_auto__add_field_follow_actor_only.py#L59

The varchar/int logic will probably be more complex and introduce some other unseen issues so im debating about whether it's a good idea or not.
