### ISSUE TITLE
More usage examples in the docs 

### ISSUE THREAD

**Issue by archatas** [justquick/django-activity-stream#264]
I find it unclear what is the difference between __action object__ and __target__. Can you please add more usage examples in the docs? About 8-10 different examples would make the documentation much better.

For example, if we have the following:
John (actor) recommended (verb) “The Matrix” to Tom 12 hours ago

What is the target here? "The Matrix" or Tom?
What is the action object? Recommendation itself, or the movie, or Tom?

**Comment by sashahart** [comment]
I apologize for butting in, but I wonder if this helps:

The README gives this example: "For example: justquick (actor) closed (verb) issue 2 (object) on django-activity-stream (target) 12 hours ago"

Next README says "Nomenclature of this specification is based on the Activity Streams Spec: http://activitystrea.ms/" Which probably explains why it is confusing, since the meanings of the terms are technical and come from a published spec.

However, the word "target" is specifically from the atom spec: http://activitystrea.ms/specs/atom/1.0/#activity.target

> The target of an activity is an Object Construct that represents the object to which the activity was performed. The exact meaning of an activity's target is dependent on the verb of the activity, but will often be the object of the English preposition "to". For example, in the activity "John saved a movie to his wishlist", the target of the activity is "wishlist". The activity target MUST NOT be used to identify an indirect object that is not a target of the activity. An Activity construct MAY have a target but it MUST NOT have more than one.

So, this jargon matches up with the English grammar ideas of "subject" (actor) "verb" (verb)  "direct object" (object) and "indirect object" (target).

Given the above, would simply reproducing the README example somewhere else help to solve this problem?

**Comment by justquick** [comment]
yea i think that's a good idea. i think also a crash course in the terminology from the spec like you have above would be helpful
