### ISSUE TITLE
RemovedInDjango110Warning: SubfieldBase has been deprecated.

### ISSUE THREAD

**Issue by hanuprateek** [justquick/django-activity-stream#292]
After upgrading to django 1.9 started seeing this warning when using JSONField.

"RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead."

**Comment by cjerdonek** [comment]
For people coming to this issue, `django-jsonfield` is required by using custom data on your actions: http://django-activity-stream.readthedocs.io/en/latest/installation.html#add-extra-data-to-actions

**Comment by justquick** [comment]
@cjerdonek i love it when people link to my docs so i dont have to. django-jsonfield is a 3rd party app so i cannot control their warnings

**Comment by cjerdonek** [comment]
@justquick, no problem!

By the way, here's the django-jsonfield issue about it: https://bitbucket.org/schinckel/django-jsonfield/issues/46/django-190-complains-about-subfieldbase

Since django-activity-stream is actively [using django-jsonfield](https://github.com/justquick/django-activity-stream/blob/e699ecea7c31d11eec5c20c4e3306eaba4d7b9b7/actstream/apps.py#L31), it could help for you to be aware of and/or contribute to the conversation there.

For example, one of the repo owners [said earlier](https://bitbucket.org/schinckel/django-jsonfield/issues/46/django-190-complains-about-subfieldbase#comment-24473440)--

> For what it's worth: if you are using Postgres, you should move to django.contrib.postgres' JSONField.

If he knows that important apps like yours depend on JSONField (and won't be changing), he could be more motivated to issue a new release.

**Comment by justquick** [comment]
super hot. going to work on a JSONField compat that can fall back to django.contrib.postgres.fields.JSONField

**Comment by cjerdonek** [comment]
Awesome! 👍

**Comment by blag** [comment]
@justquick: If possible, you may want to try to upstream your compat wrapper to django.contrib.postgres.

**Comment by cjerdonek** [comment]
FYI, so people on this thread know, [django-jsonfield](https://bitbucket.org/schinckel/django-jsonfield/) [released](https://pypi.python.org/pypi/django-jsonfield) version 1.0.0 yesterday which made the warning go away.
