### ISSUE TITLE
Guideline to assign action target and object?

### ISSUE THREAD

**Issue by wyx2000** [justquick/django-activity-stream#298]
For example, under one donation event, I add a donation from user A, what should assign to target and object?  donation event to target or user A to target?

Another thing is if I assign target or object, it seems I cannot delete them, for example, if I assign user A to action object, after user A is deleted, the action will be disappeared too. Is that by design? seems not quite right, I still want to see activities of an object even it is deleted.

**Comment by justquick** [comment]
id have:

- actor: donor
- target: what you are donating to
- object: the donation object itself (this might not b necessary)

The way django GFKs work is if you delete anything from the db it will remove the reference. This is by django's design. You could implement a deleted flag on your models and use that instead of deleting the record entirely
