### ISSUE TITLE
Actstream unusable if you set USE_JSONFIELD to True after installation

### ISSUE THREAD

**Issue by encolpe** [justquick/django-activity-stream#304]
In the migration 0002 you have:

``` python
    if not USE_JSONFIELD:
        operations = [
            migrations.RemoveField(
                model_name='action',
                name='data',
),
```

Consider the following use case:
- assumption USE_JSONFIELD is False by default
- You install activity-stream and run the initial migration
- You set **USE_JSONFIELD** to _True_

Now, each operation raise an SQL error because data column is missing.

If you rollback 0002 when **USE_JSONFIELD** is _True_ it will not fix the problem. You need to rollback to 0001 with **USE_JSONFIELD** set to _False_ then change **USE_JSONFIELD** to _True_ and reroll 0002 migration.

May this condition can be removed.

Regards

**Comment by justquick** [comment]
conditional migrations are pretty tricky. also i think you are taking into account that people would be changing the value of USE_JSONFIELD in their settings. I would suggest that people set it once, migrate, and then dont change it.

if you have some changes to the migrations that would b helpful please make a PR

**Comment by jsma** [comment]
When #294 lands, I might be in this exact situation: I started a project with `USE_JSONFIELD = False` to avoid the dependency on `jsonfield`, but I'll want to enable it once native PostgreSQL JSONField is supported.

Had you previously considered merely providing an abstract base class a la custom user model as opposed to conditionally adding model fields based on a setting? 

I'm sure there are complexities I'm unaware of but it seems like this would mean you could avoid including migrations at all for the model and users would be free to add their own extra fields. The `action` signal could then just pass the kwargs during creation. Backwards incompatible, but might be able to at least document the steps to transition (create subclass, set db_table, etc.). Thoughts?

I could put together a PR if this sounds like a workable approach.

**Comment by justquick** [comment]
Im not sure whether an abstract base class would get you out of the problems you have now with moving to postgres json fields since those changes would be to the base Action class anyway. 

That being said, I think that there are other opportunities where this level of extension would be helpful so please go ahead and make a PR

**Comment by jsma** [comment]
I wasn't clear in my previous comment but I was thinking the 'data' field wouldn't be a part of the base class at all. If users want a JSONField or any other fields, they would just add the fields to their subclass and do their own migrations and be responsible for passing the extra data through `action.send(**kwargs)`. 

So if you wanted just a single JSONField for 'data', you'd have to explicitly pass `data = {'custom_key': 'custom value',}` as one of the kwargs and `action_handler` would simply pass this in during creation rather than capturing all remaining kwargs and stuffing it in the 'data' field.

Does that make sense? It's definitely not backwards compatible, but seemed more flexible.

**Comment by stevelacey** [comment]
A major version bump (1.0? :O) and dropping migrations would be something I would +1 all over, as a repeat user of this library, I'd be happy to endure the painful migration this would require for existing users – abstract would be far more flexible IMO – I'd encourage it for the `Follow` class too, why not.

I always found it weird this library opts for providing migrations rather than going down the same route as Django contrib auth.

**Comment by afgonzalezgarcia** [comment]
Hi every one? Any update to solve this usse? Regards

**Comment by cb109** [comment]
Just ran into this today. We've been using the library for a year and now want to extend usage by attaching data via a JSONField. Docs say 

> This behavior is disabled by default but just set ACTSTREAM_SETTINGS['USE_JSONFIELD'] = True in your settings.py to enable it.

Well that is only true if you never ran migrations in the first place, it's basically an invitation to get stuck and I think both docs as the process itself can be improved. How about removing this 0002 migrations altogether, what purpose does it have? Is it an optimization, sparing us a column in the database? No big deal for me honestly.

**Comment by auvipy** [comment]
@cb109 how about removing and regenerating new migrations to avoid the 2nd migration? or do you have any other better suggestion in mind?

**Comment by cb109** [comment]
This would help with people changing their mind whether they want to use the `data` field later on. However they'd still have to make the right decision in choosing an implementation in the first place, so that the field type does not have to be changed later. That would require an installation of one of the `JSONField` packages, making it a hard dependency instead of an optional one. I think the default case should cater to most people and I believe that this would be an improvement over the current approach.

I would say `USE_JSONFIELD` is obsolete and can go away, instead we always create a `data` field during initial migrations and make it a `jsonfield.fields.JSONField` by default (or optionally a `django_mysql.models.json.JSONField`, depending on installed packages). That would make `django-jsonfield` a default requirement, which I think is okay (it's a pure python package in the end).

Migration 0002 could be removed. Maybe it would be possible to prompt the user during initial migrations, explaining the decision he is about to make for the `JSONField` implementation. Not sure if this "interrupting" migration is something feasible to do. Other than that, any changes that need to be done later would be covered once the swappable models are in place, allowing to migrate field types inside your own application at a later time.

I may have missed something, so other opinions on this would be helpful.
