### ISSUE TITLE
ImportError: cannot import salons.managers.MyActionManager. try fixing ACRSTREAM_SETTINGS[MANAGAER]setting

### ISSUE THREAD

**Issue by silasseB** [justquick/django-activity-stream#347]
here i my settings.py

ACTSTREAM_SETTINGS =  {
                                       'MANAGER': 'salons.managers.MyActionManager'
                                       'FECTH_RELATIONS' : True,
                                       'USE_JSONFIELD' :True,
}

and my managers.py

from datetime   import   datetime
from django.contrib.contenttypes.models    import   ContentType
from actstream.managers  import  ActionManager,  stream

class MyActionManager(ActionManager):

        @stream
        def ready(self, obj,   verb = posted, time =None):
                  if time is None:
                       time = datetime.now()
                  return  obj.actor_actions.filter(verb = verb, timestamp = time__lte=time

and my __init__.py
default_apps_config = 'salons.apps.SalonsConfig'

and finaly my apps.py

from django.apps import AppConfig

class SalonsApp(AppConfig):
         name = 'salons'

          def ready(self):
                  from actstream import registry
                  registry.register(self.get_model('salonProfile')

`I have been stuck here for two todays now, please anyone help me

**Comment by cmwaura** [comment]
what directory does manager.py live in?

**Comment by cmwaura** [comment]
@auvipy we should close this issue

**Comment by ajakubo1** [comment]
So - in case someone encounters this problem.

I am using a custom manager for ACTSTREAM and suddenly the import started failing. Turns out - the problem was triggered by another error, which was covered-up by ``try fixing ACRSTREAM_SETTINGS[MANAGAER]setting`` error.

To properly address this - I removed the custom manager from the setting and that allowed me to search for the original problem.

However - I would say that it would be nice if the import code didn't cover up the original error?

I believe that this:

```python
def import_obj(mod):
    mod_path = mod.split('.')
    try:
        obj = __import__('.'.join(mod_path[:-1]), {}, {}, [mod_path[-1]])
        return getattr(obj, mod_path[-1])
    except:
        raise ImportError(f'Cannot import: {mod}')
```

should not explicitly catch everything and raise ImportError.
