### ISSUE TITLE
The enhancement of Follow model has some remaining issues that need to be discussed

### ISSUE THREAD

**Issue by ghost** [justquick/django-activity-stream#368]
Thank for merging my pull requests of enhancing `Follow` model #345 and sorry for suspending the works #317  for a long time.

Now, winter holiday will come and I will have some time to continue my unfinished work. I'm glad to say that works almost finished and only remains some issues that need to be discussed to find better solutions. Here are the issuses.

1. How to set action verb?

```
    if send_action and created:
        if not flag:
            action.send(user, verb=_('started following'), target=obj, **kwargs)
        else:
            action.send(user, verb=_('started %s' % flag), target=obj, **kwargs)
```
In previous version, there is only one type of follow which is follow itself and we can mark the follow action with verb 'started following'. But in the new version, there are a lot of type of follow such as 'like', 'watch', etc. User passes a string value to flag argument to set the follow type. Then we send a signal to create a action. But the transformation rules of verbs many be diverse. For examle, like->liking, watch->watching. So how to set correct verb form for user?

2. About template tags

May be for some compatibilites, we write template tags from scratch. Actually, since django1.8 we can replace all template tags with django build-in `simple_tag` to achieve the same result . If #333 finished, we can do that things.

3. Documentations
Add such new features to the documentation.

So, if we have any plan to address above issuses and release in future version. I'm glad to give my little effort.

**Comment by zmrenwu** [comment]
@auvipy Any suggestions?

**Comment by auvipy** [comment]
X started following/watching

**Comment by auvipy** [comment]
#333 is done. 6.5 is released. So master is a test bed now. next release will be focuing on v2.0 v1.11 mainly. you can start your work and send a PR with incremental updates. SO that I can provide early feedback and help in design decision.

**Comment by auvipy** [comment]
flag=' ' invalid syntax error in master, any thoughts on that? what about flag=None instead of ''? and in logisc if flag is not None:
.....

**Comment by zmrenwu** [comment]
I have no idea about the syntax error. `flag` must be a empty string when do database query.

About the tense of verb issue, I have some new idea recently. Let see the source code:

```
    if send_action and created:
        if not flag:
            action.send(user, verb=_('started following'), target=obj, **kwargs)
        else:
            action.send(user, verb=_('started %s' % flag), target=obj, **kwargs)
```

A `flag` is a sign which used to differentiate the `Follow` type, since there are lots of follow relations in some cases especially for social  network websites, such as 'like'--user like a comment or 'watch'--user watch another user etc..

When a sort of  `Follow` was created, we send a action signal with `verb=started doing something`. Previously, we just set verb to `started following`, a broad action verb. But now we need a more exact verb. For example, `verb=started liking`, when user likes a comment; or `verb=started watching`.

The value of `verb` based on `flag`. But flag usually a noun or a base form of verb set by client, such as like, watch, follow. So we need a verb transformer to do some  verb transformation. My idea is defining a `Transformer` class that can transform a base form of verb to it;s progressive tense or passive tense. For example:

```
class DefualtVerbTransformer(object):
    def trans(verb):
          # Transform a base form verb to it's progressive tense
          # Note that verb tense transformation does not follow a unique rule, for example, like->liking,
          # watch->watching, get->getting
```

Then we set it on setting:

```
ACTSTREAM_VERB_TRANSFORMER = 'DefualtVerbTransformer'。
```

Verb tense transformation is a complex problem. We allow developer subclass `VerbTransformer` and define special transformation rules:

```
ACTSTREAM_DEFUALT_VERB_TRANSFORMER = 'CustomVerbTransformer'。
```
