### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by walterl** [justquick/django-activity-stream#375]
Evaluation Django Activity Stream for use, I almost had a heart attack when I read in the [official documentation](https://django-activity-stream.readthedocs.io/en/latest/installation.html) that only Django versions 1.3 - 1.9 are supported. Luckily I kept breathing long enough to check the [current documentation](https://github.com/justquick/django-activity-stream/blob/master/docs/source/installation.rst#django), which seems to be more up-to-date.

Can we avoid any further cardiac emergencies by updating the documentation over at readthedocs.io, please? :)

**Comment by elcolie** [comment]
What is IRI?
http://django-activity-stream.readthedocs.io/en/latest/concepts.html
I have followed the given link but it is dead

**Comment by morenoh149** [comment]
the doc is update in the repo https://github.com/justquick/django-activity-stream/blob/master/docs/source/installation.rst but not on the live site https://django-activity-stream.readthedocs.io/en/latest/installation.html#django maybe update the live site to close this issue?

**Comment by chescales** [comment]
Hey yes could this be re-deployed please? The docs are like 2 years old I guess (it says 2017 in there). Thank you! :pray:

**Comment by C4ptainCrunch** [comment]
It seems like there are 2 issues here:
 * The last build was in 2018. This most likely indicates that the webhook from GitHub to rtfd is broken.
 * The last build failed ([logs](https://readthedocs.org/projects/django-activity-stream/builds/8263768/)) due to an import error
 
While in can't do anything to fix the first issue without ownership of the rtfd project, once issue 1 is fixed i could have a look at issue 2 if you want. Is this something you would be interested in @auvipy ?
