### ISSUE TITLE
User Stream Does Not Bring Following User's Action

### ISSUE THREAD

**Issue by eermis1** [justquick/django-activity-stream#458]
Hi 
I tried to build a **User Stream** as described in [here](https://django-activity-stream.readthedocs.io/en/latest/streams.html). 
To do so, firstly I just implemented the **def stream(request)** function on the this repo's view then got only the user's feed , that is OK.

> admin started following evrenermis 10 minutes ago
admin started following İzmit Covid-19 Durumu 49 minutes ago
admin Has Created A New Post - İzmit Covid-19 Durumu 51 minutes ago
admin started following admin 53 minutes ago
admin started following Covid-19 İle Mücadele 54 minutes ago
admin Has Created A New Community - Covid-19 İle Mücadele 58 minutes ago

But when I wanted to see also the following user's activity, I implemented the User Stream as [here](https://django-activity-stream.readthedocs.io/en/latest/streams.html). 

`def stream(request):
    
    return render(request, 'stream.html',
                  context={
            'ctype': ContentType.objects.get_for_model(USER_MODEL),
            'actor': request.user,
            'action_list': user_stream(request.user, with_user_activity=True)
        }
    )`

but still I receive only the user's feed without any following activities. 

I would be glad if you could explain how to implement the User Stream 

Many thanks in advance

**Comment by cb109** [comment]
@eermis1 As far as I understand, `user_stream` works the opposite way: It will list Actions from objects that **you** follow, not the Actions of people that follow you.

You can aggregate those by combining two of the builtin helpers:
```py

from django.contrib.auth.models import User
from actstream.models import followers, actor_stream

myself = User.objects.get(username="myself")
for follower in followers(myself):
    follower_actions = actor_stream(follower)

```

It may also be helpful to take a look at how those helpers are implemented: https://github.com/justquick/django-activity-stream/blob/master/actstream/managers.py

If that doesn't fit, you can always write your own query for `Action`, it's just a bit fiddly since you have to supply a `ContentType`. 

Example:
```py

from actstream.models import Action
from django.contrib.contenttypes.models import ContentType

actions = Action.objects.filter(
  actor_object_id=user.id,
  action_object_object_id=my_model_instance.id,
  action_object_content_type_id=ContentType.objects.get_for_model(MyModel),
  verb="liked",
)

```
